/* soapStub.h
   Generated by gSOAP 2.8.16 from cwmp.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_cwmp	"urn:dslforum-org:cwmp-1-0"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20816
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (7)
/* xsd:boolean */
enum xsd__boolean { xsd__boolean__false_ = 0, xsd__boolean__true_ = 1 };
#endif

#ifndef SOAP_TYPE_cwmp__SetParameterAttributesStruct_Notification
#define SOAP_TYPE_cwmp__SetParameterAttributesStruct_Notification (11)
/* cwmp:SetParameterAttributesStruct-Notification */
enum cwmp__SetParameterAttributesStruct_Notification { cwmp__SetParameterAttributesStruct_Notification__0 = 0, cwmp__SetParameterAttributesStruct_Notification__1 = 1, cwmp__SetParameterAttributesStruct_Notification__2 = 2 };
#endif

#ifndef SOAP_TYPE_cwmp__SetParameterValuesResponse_Status
#define SOAP_TYPE_cwmp__SetParameterValuesResponse_Status (12)
/* cwmp:SetParameterValuesResponse-Status */
enum cwmp__SetParameterValuesResponse_Status { cwmp__SetParameterValuesResponse_Status__0 = 0, cwmp__SetParameterValuesResponse_Status__1 = 1 };
#endif

#ifndef SOAP_TYPE_cwmp__ParameterAttributeStruct_Notification
#define SOAP_TYPE_cwmp__ParameterAttributeStruct_Notification (13)
/* cwmp:ParameterAttributeStruct-Notification */
enum cwmp__ParameterAttributeStruct_Notification { cwmp__ParameterAttributeStruct_Notification__0 = 0, cwmp__ParameterAttributeStruct_Notification__1 = 1, cwmp__ParameterAttributeStruct_Notification__2 = 2 };
#endif

#ifndef SOAP_TYPE_cwmp__AddObjectResponse_Status
#define SOAP_TYPE_cwmp__AddObjectResponse_Status (14)
/* cwmp:AddObjectResponse-Status */
enum cwmp__AddObjectResponse_Status { cwmp__AddObjectResponse_Status__0 = 0, cwmp__AddObjectResponse_Status__1 = 1 };
#endif

#ifndef SOAP_TYPE_cwmp__DeleteObjectResponse_Status
#define SOAP_TYPE_cwmp__DeleteObjectResponse_Status (15)
/* cwmp:DeleteObjectResponse-Status */
enum cwmp__DeleteObjectResponse_Status { cwmp__DeleteObjectResponse_Status__0 = 0, cwmp__DeleteObjectResponse_Status__1 = 1 };
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_cwmp__FaultStruct
#define SOAP_TYPE_cwmp__FaultStruct (16)
/* cwmp:FaultStruct */
struct cwmp__FaultStruct
{
	char *FaultCode;	/* required element of type xsd:string */
	char *FaultString;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp__MethodList
#define SOAP_TYPE_cwmp__MethodList (17)
/* cwmp:MethodList */
struct cwmp__MethodList
{
	int __sizestring;	/* sequence of elements <string> */
	char **string;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp__ParameterValueStruct
#define SOAP_TYPE_cwmp__ParameterValueStruct (19)
/* cwmp:ParameterValueStruct */
struct cwmp__ParameterValueStruct
{
	char *Name;	/* required element of type xsd:string */
	char *Value;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp__SetParameterAttributesStruct
#define SOAP_TYPE_cwmp__SetParameterAttributesStruct (20)
/* cwmp:SetParameterAttributesStruct */
struct cwmp__SetParameterAttributesStruct
{
	char *Name;	/* optional element of type xsd:string */
	enum xsd__boolean NotificationChange;	/* required element of type xsd:boolean */
	enum cwmp__SetParameterAttributesStruct_Notification Notification;	/* required element of type cwmp:SetParameterAttributesStruct-Notification */
	char *AccessListChange;	/* required element of type xsd:string */
	struct cwmpArrayOfstring *AccessList;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_cwmp__EventStruct
#define SOAP_TYPE_cwmp__EventStruct (23)
/* cwmp:EventStruct */
struct cwmp__EventStruct
{
	char *EventCode;	/* required element of type xsd:string */
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE_cwmp__ParameterInfoStruct
#define SOAP_TYPE_cwmp__ParameterInfoStruct (24)
/* cwmp:ParameterInfoStruct */
struct cwmp__ParameterInfoStruct
{
	char *Name;	/* required element of type xsd:string */
	int Writable;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_cwmp__ParameterAttributeStruct
#define SOAP_TYPE_cwmp__ParameterAttributeStruct (25)
/* cwmp:ParameterAttributeStruct */
struct cwmp__ParameterAttributeStruct
{
	char *Name;	/* required element of type xsd:string */
	enum cwmp__ParameterAttributeStruct_Notification Notification;	/* required element of type cwmp:ParameterAttributeStruct-Notification */
	struct cwmpArrayOfstring *AccessList;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_cwmp__DeviceIdStruct
#define SOAP_TYPE_cwmp__DeviceIdStruct (26)
/* cwmp:DeviceIdStruct */
struct cwmp__DeviceIdStruct
{
	char *Manufacturer;	/* optional element of type xsd:string */
	char *OUI;	/* optional element of type xsd:string */
	char *ProductClass;	/* optional element of type xsd:string */
	char *SerialNumber;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__Inform
#define SOAP_TYPE__cwmp__Inform (27)
/* cwmp:Inform */
struct _cwmp__Inform
{
	struct cwmp__DeviceIdStruct *DeviceId;	/* optional element of type cwmp:DeviceIdStruct */
	struct cwmpArrayOfEventStruct *Event;	/* optional element of type ArrayOfEventStruct */
	unsigned int MaxEnvelopes;	/* required element of type xsd:unsignedInt */
	char *CurrentTime;	/* optional element of type xsd:string */
	unsigned int RetryCount;	/* required element of type xsd:unsignedInt */
	struct cwmpArrayOfParameterValueStruct *ParameterList;	/* optional element of type ArrayOfParameterValueStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__InformResponse
#define SOAP_TYPE__cwmp__InformResponse (34)
/* cwmp:InformResponse */
struct _cwmp__InformResponse
{
	unsigned int MaxEnvelopes;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetRPCMethods
#define SOAP_TYPE__cwmp__GetRPCMethods (35)
/* cwmp:GetRPCMethods */
struct _cwmp__GetRPCMethods
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetRPCMethodsResponse
#define SOAP_TYPE__cwmp__GetRPCMethodsResponse (36)
/* cwmp:GetRPCMethodsResponse */
struct _cwmp__GetRPCMethodsResponse
{
	struct cwmp__MethodList *MethodList;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type cwmp:MethodList */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterValues
#define SOAP_TYPE__cwmp__GetParameterValues (38)
/* cwmp:GetParameterValues */
struct _cwmp__GetParameterValues
{
	struct cwmpArrayOfstring *ParameterNames;	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterValuesResponse
#define SOAP_TYPE__cwmp__GetParameterValuesResponse (39)
/* cwmp:GetParameterValuesResponse */
struct _cwmp__GetParameterValuesResponse
{
	struct cwmpArrayOfParameterValueStruct *ParameterList;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfParameterValueStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterValues
#define SOAP_TYPE__cwmp__SetParameterValues (40)
/* cwmp:SetParameterValues */
struct _cwmp__SetParameterValues
{
	struct cwmpArrayOfParameterValueStruct *ParameterList;	/* optional element of type ArrayOfParameterValueStruct */
	char *ParameterKey;	/* optional element of type cwmp:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterValuesResponse
#define SOAP_TYPE__cwmp__SetParameterValuesResponse (41)
/* cwmp:SetParameterValuesResponse */
struct _cwmp__SetParameterValuesResponse
{
	enum cwmp__SetParameterValuesResponse_Status Status;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type cwmp:SetParameterValuesResponse-Status */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterNames
#define SOAP_TYPE__cwmp__GetParameterNames (42)
/* cwmp:GetParameterNames */
struct _cwmp__GetParameterNames
{
	char *ParameterPath;	/* optional element of type xsd:string */
	char *NextLevel;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterNamesResponse
#define SOAP_TYPE__cwmp__GetParameterNamesResponse (43)
/* cwmp:GetParameterNamesResponse */
struct _cwmp__GetParameterNamesResponse
{
	struct cwmpArrayOfParameterInfoStruct *ParameterList;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfParameterInfoStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterAttributes
#define SOAP_TYPE__cwmp__SetParameterAttributes (46)
/* cwmp:SetParameterAttributes */
struct _cwmp__SetParameterAttributes
{
	struct cwmpArrayOfSetParameterAttributesStruct *ParameterList;	/* optional element of type ArrayOfSetParameterAttributesStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__SetParameterAttributesResponse
#define SOAP_TYPE__cwmp__SetParameterAttributesResponse (49)
/* cwmp:SetParameterAttributesResponse */
struct _cwmp__SetParameterAttributesResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterAttributes
#define SOAP_TYPE__cwmp__GetParameterAttributes (50)
/* cwmp:GetParameterAttributes */
struct _cwmp__GetParameterAttributes
{
	struct cwmpArrayOfstring *ParameterNames;	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE__cwmp__GetParameterAttributesResponse
#define SOAP_TYPE__cwmp__GetParameterAttributesResponse (51)
/* cwmp:GetParameterAttributesResponse */
struct _cwmp__GetParameterAttributesResponse
{
	struct cwmpArrayOfParameterAttributeStruct *ParameterList;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfParameterAttributeStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp__AddObject
#define SOAP_TYPE__cwmp__AddObject (54)
/* cwmp:AddObject */
struct _cwmp__AddObject
{
	char *ObjectName;	/* optional element of type cwmp:ObjectNameType */
	char *ParameterKey;	/* optional element of type cwmp:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__AddObjectResponse
#define SOAP_TYPE__cwmp__AddObjectResponse (55)
/* cwmp:AddObjectResponse */
struct _cwmp__AddObjectResponse
{
	unsigned int InstanceNumber;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:unsignedInt */
	enum cwmp__AddObjectResponse_Status Status;	/* required element of type cwmp:AddObjectResponse-Status */
};
#endif

#ifndef SOAP_TYPE__cwmp__DeleteObject
#define SOAP_TYPE__cwmp__DeleteObject (56)
/* cwmp:DeleteObject */
struct _cwmp__DeleteObject
{
	char *ObjectName;	/* optional element of type cwmp:ObjectNameType */
	char *ParameterKey;	/* optional element of type cwmp:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__DeleteObjectResponse
#define SOAP_TYPE__cwmp__DeleteObjectResponse (57)
/* cwmp:DeleteObjectResponse */
struct _cwmp__DeleteObjectResponse
{
	enum cwmp__DeleteObjectResponse_Status Status;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type cwmp:DeleteObjectResponse-Status */
};
#endif

#ifndef SOAP_TYPE__cwmp__Reboot
#define SOAP_TYPE__cwmp__Reboot (58)
/* cwmp:Reboot */
struct _cwmp__Reboot
{
	char *CommandKey;	/* optional element of type cwmp:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__RebootResponse
#define SOAP_TYPE__cwmp__RebootResponse (59)
/* cwmp:RebootResponse */
struct _cwmp__RebootResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__Download
#define SOAP_TYPE__cwmp__Download (60)
/* cwmp:Download */
struct _cwmp__Download
{
	char *CommandKey;	/* optional element of type cwmp:CommandKeyType */
	char *FileType;	/* optional element of type xsd:string */
	char *URL;	/* optional element of type xsd:string */
	char *Username;	/* optional element of type xsd:string */
	char *Password;	/* optional element of type xsd:string */
	int FileSize;	/* required element of type xsd:int */
	char *TargetFileName;	/* optional element of type xsd:string */
	int DelaySeconds;	/* required element of type xsd:int */
	char *SuccessURL;	/* optional element of type xsd:string */
	char *FailureURL;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__DownloadResponse
#define SOAP_TYPE__cwmp__DownloadResponse (61)
/* cwmp:DownloadResponse */
struct _cwmp__DownloadResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__Upload
#define SOAP_TYPE__cwmp__Upload (62)
/* cwmp:Upload */
struct _cwmp__Upload
{
	char *CommandKey;	/* optional element of type cwmp:CommandKeyType */
	char *FileType;	/* optional element of type xsd:string */
	char *URL;	/* optional element of type xsd:string */
	char *Username;	/* optional element of type xsd:string */
	char *Password;	/* optional element of type xsd:string */
	int DelaySeconds;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__cwmp__UploadResponse
#define SOAP_TYPE__cwmp__UploadResponse (63)
/* cwmp:UploadResponse */
struct _cwmp__UploadResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__FactoryReset
#define SOAP_TYPE__cwmp__FactoryReset (64)
/* cwmp:FactoryReset */
struct _cwmp__FactoryReset
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__FactoryResetResponse
#define SOAP_TYPE__cwmp__FactoryResetResponse (65)
/* cwmp:FactoryResetResponse */
struct _cwmp__FactoryResetResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__ScheduleInform
#define SOAP_TYPE__cwmp__ScheduleInform (66)
/* cwmp:ScheduleInform */
struct _cwmp__ScheduleInform
{
	int DelaySeconds;	/* required element of type xsd:int */
	char *CommandKey;	/* optional element of type cwmp:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp__ScheduleInformResponse
#define SOAP_TYPE__cwmp__ScheduleInformResponse (67)
/* cwmp:ScheduleInformResponse */
struct _cwmp__ScheduleInformResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__TranferComplete
#define SOAP_TYPE__cwmp__TranferComplete (68)
/* cwmp:TranferComplete */
struct _cwmp__TranferComplete
{
	char *CommandKey;	/* optional element of type cwmp:CommandKeyType */
	struct cwmp__FaultStruct *FaultStruct;	/* required element of type cwmp:FaultStruct */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__cwmp__TranferCompleteResponse
#define SOAP_TYPE__cwmp__TranferCompleteResponse (71)
/* cwmp:TranferCompleteResponse */
struct _cwmp__TranferCompleteResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_cwmpArrayOfstring
#define SOAP_TYPE_cwmpArrayOfstring (21)
/* SOAP encoded array of xsd:string schema type: */
struct cwmpArrayOfstring
{
	char **__ptrstring;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmpArrayOfSetParameterAttributesStruct
#define SOAP_TYPE_cwmpArrayOfSetParameterAttributesStruct (47)
/* SOAP encoded array of cwmp:SetParameterAttributesStruct schema type: */
struct cwmpArrayOfSetParameterAttributesStruct
{
	struct cwmp__SetParameterAttributesStruct **__ptrSetParameterAttributesStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmpArrayOfParameterInfoStruct
#define SOAP_TYPE_cwmpArrayOfParameterInfoStruct (44)
/* SOAP encoded array of cwmp:ParameterInfoStruct schema type: */
struct cwmpArrayOfParameterInfoStruct
{
	struct cwmp__ParameterInfoStruct **__ptrParameterInfoStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmpArrayOfParameterAttributeStruct
#define SOAP_TYPE_cwmpArrayOfParameterAttributeStruct (52)
/* SOAP encoded array of cwmp:ParameterAttributeStruct schema type: */
struct cwmpArrayOfParameterAttributeStruct
{
	struct cwmp__ParameterAttributeStruct **__ptrParameterAttributeStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmpArrayOfEventStruct
#define SOAP_TYPE_cwmpArrayOfEventStruct (29)
/* SOAP encoded array of cwmp:EventStruct schema type: */
struct cwmpArrayOfEventStruct
{
	struct cwmp__EventStruct **__ptrEventStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmpArrayOfParameterValueStruct
#define SOAP_TYPE_cwmpArrayOfParameterValueStruct (32)
/* SOAP encoded array of cwmp:ParameterValueStruct schema type: */
struct cwmpArrayOfParameterValueStruct
{
	struct cwmp__ParameterValueStruct **__ptrParameterValueStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE___cwmp__Inform
#define SOAP_TYPE___cwmp__Inform (85)
/* Operation wrapper: */
struct __cwmp__Inform
{
	struct _cwmp__Inform *cwmp__Inform;	/* optional element of type cwmp:Inform */
};
#endif

#ifndef SOAP_TYPE___cwmp__GetRPCMethods
#define SOAP_TYPE___cwmp__GetRPCMethods (89)
/* Operation wrapper: */
struct __cwmp__GetRPCMethods
{
	struct _cwmp__GetRPCMethods *cwmp__GetRPCMethods;	/* optional element of type cwmp:GetRPCMethods */
};
#endif

#ifndef SOAP_TYPE___cwmp__GetParameterValues
#define SOAP_TYPE___cwmp__GetParameterValues (93)
/* Operation wrapper: */
struct __cwmp__GetParameterValues
{
	struct _cwmp__GetParameterValues *cwmp__GetParameterValues;	/* optional element of type cwmp:GetParameterValues */
};
#endif

#ifndef SOAP_TYPE___cwmp__SetParameterValues
#define SOAP_TYPE___cwmp__SetParameterValues (97)
/* Operation wrapper: */
struct __cwmp__SetParameterValues
{
	struct _cwmp__SetParameterValues *cwmp__SetParameterValues;	/* optional element of type cwmp:SetParameterValues */
};
#endif

#ifndef SOAP_TYPE___cwmp__GetParameterNames
#define SOAP_TYPE___cwmp__GetParameterNames (101)
/* Operation wrapper: */
struct __cwmp__GetParameterNames
{
	struct _cwmp__GetParameterNames *cwmp__GetParameterNames;	/* optional element of type cwmp:GetParameterNames */
};
#endif

#ifndef SOAP_TYPE___cwmp__SetParameterAttributes
#define SOAP_TYPE___cwmp__SetParameterAttributes (105)
/* Operation wrapper: */
struct __cwmp__SetParameterAttributes
{
	struct _cwmp__SetParameterAttributes *cwmp__SetParameterAttributes;	/* optional element of type cwmp:SetParameterAttributes */
};
#endif

#ifndef SOAP_TYPE___cwmp__GetParameterAttributes
#define SOAP_TYPE___cwmp__GetParameterAttributes (109)
/* Operation wrapper: */
struct __cwmp__GetParameterAttributes
{
	struct _cwmp__GetParameterAttributes *cwmp__GetParameterAttributes;	/* optional element of type cwmp:GetParameterAttributes */
};
#endif

#ifndef SOAP_TYPE___cwmp__AddObject
#define SOAP_TYPE___cwmp__AddObject (113)
/* Operation wrapper: */
struct __cwmp__AddObject
{
	struct _cwmp__AddObject *cwmp__AddObject;	/* optional element of type cwmp:AddObject */
};
#endif

#ifndef SOAP_TYPE___cwmp__DeleteObject
#define SOAP_TYPE___cwmp__DeleteObject (117)
/* Operation wrapper: */
struct __cwmp__DeleteObject
{
	struct _cwmp__DeleteObject *cwmp__DeleteObject;	/* optional element of type cwmp:DeleteObject */
};
#endif

#ifndef SOAP_TYPE___cwmp__Reboot
#define SOAP_TYPE___cwmp__Reboot (121)
/* Operation wrapper: */
struct __cwmp__Reboot
{
	struct _cwmp__Reboot *cwmp__Reboot;	/* optional element of type cwmp:Reboot */
};
#endif

#ifndef SOAP_TYPE___cwmp__Download
#define SOAP_TYPE___cwmp__Download (125)
/* Operation wrapper: */
struct __cwmp__Download
{
	struct _cwmp__Download *cwmp__Download;	/* optional element of type cwmp:Download */
};
#endif

#ifndef SOAP_TYPE___cwmp__Upload
#define SOAP_TYPE___cwmp__Upload (129)
/* Operation wrapper: */
struct __cwmp__Upload
{
	struct _cwmp__Upload *cwmp__Upload;	/* optional element of type cwmp:Upload */
};
#endif

#ifndef SOAP_TYPE___cwmp__FactoryReset
#define SOAP_TYPE___cwmp__FactoryReset (133)
/* Operation wrapper: */
struct __cwmp__FactoryReset
{
	struct _cwmp__FactoryReset *cwmp__FactoryReset;	/* optional element of type cwmp:FactoryReset */
};
#endif

#ifndef SOAP_TYPE___cwmp__ScheduleInform
#define SOAP_TYPE___cwmp__ScheduleInform (137)
/* Operation wrapper: */
struct __cwmp__ScheduleInform
{
	struct _cwmp__ScheduleInform *cwmp__ScheduleInform;	/* optional element of type cwmp:ScheduleInform */
};
#endif

#ifndef SOAP_TYPE___cwmp__TranferComplete
#define SOAP_TYPE___cwmp__TranferComplete (141)
/* Operation wrapper: */
struct __cwmp__TranferComplete
{
	struct _cwmp__TranferComplete *cwmp__TranferComplete;	/* optional element of type cwmp:TranferComplete */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (142)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
#ifdef CWMP_MUSTUNDERSTAND_SUPPORT
	char *cwmp__ID ;	/* mustUnderstand support */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (143)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (145)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (148)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (149)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_cwmp__ParameterKeyType
#define SOAP_TYPE_cwmp__ParameterKeyType (8)
typedef char *cwmp__ParameterKeyType;
#endif

#ifndef SOAP_TYPE_cwmp__ObjectNameType
#define SOAP_TYPE_cwmp__ObjectNameType (9)
typedef char *cwmp__ObjectNameType;
#endif

#ifndef SOAP_TYPE_cwmp__CommandKeyType
#define SOAP_TYPE_cwmp__CommandKeyType (10)
typedef char *cwmp__CommandKeyType;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 __cwmp__Inform(struct soap*, struct _cwmp__Inform *cwmp__Inform, struct _cwmp__InformResponse *cwmp__InformResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__GetRPCMethods(struct soap*, struct _cwmp__GetRPCMethods *cwmp__GetRPCMethods, struct _cwmp__GetRPCMethodsResponse *cwmp__GetRPCMethodsResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__GetParameterValues(struct soap*, struct _cwmp__GetParameterValues *cwmp__GetParameterValues, struct _cwmp__GetParameterValuesResponse *cwmp__GetParameterValuesResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__SetParameterValues(struct soap*, struct _cwmp__SetParameterValues *cwmp__SetParameterValues, struct _cwmp__SetParameterValuesResponse *cwmp__SetParameterValuesResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__GetParameterNames(struct soap*, struct _cwmp__GetParameterNames *cwmp__GetParameterNames, struct _cwmp__GetParameterNamesResponse *cwmp__GetParameterNamesResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__SetParameterAttributes(struct soap*, struct _cwmp__SetParameterAttributes *cwmp__SetParameterAttributes, struct _cwmp__SetParameterAttributesResponse *cwmp__SetParameterAttributesResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__GetParameterAttributes(struct soap*, struct _cwmp__GetParameterAttributes *cwmp__GetParameterAttributes, struct _cwmp__GetParameterAttributesResponse *cwmp__GetParameterAttributesResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__AddObject(struct soap*, struct _cwmp__AddObject *cwmp__AddObject, struct _cwmp__AddObjectResponse *cwmp__AddObjectResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__DeleteObject(struct soap*, struct _cwmp__DeleteObject *cwmp__DeleteObject, struct _cwmp__DeleteObjectResponse *cwmp__DeleteObjectResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__Reboot(struct soap*, struct _cwmp__Reboot *cwmp__Reboot, struct _cwmp__RebootResponse *cwmp__RebootResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__Download(struct soap*, struct _cwmp__Download *cwmp__Download, struct _cwmp__DownloadResponse *cwmp__DownloadResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__Upload(struct soap*, struct _cwmp__Upload *cwmp__Upload, struct _cwmp__UploadResponse *cwmp__UploadResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__FactoryReset(struct soap*, struct _cwmp__FactoryReset *cwmp__FactoryReset, struct _cwmp__FactoryResetResponse *cwmp__FactoryResetResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__ScheduleInform(struct soap*, struct _cwmp__ScheduleInform *cwmp__ScheduleInform, struct _cwmp__ScheduleInformResponse *cwmp__ScheduleInformResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp__TranferComplete(struct soap*, struct _cwmp__TranferComplete *cwmp__TranferComplete, struct _cwmp__TranferCompleteResponse *cwmp__TranferCompleteResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__Inform(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetRPCMethods(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetParameterValues(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__SetParameterValues(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetParameterNames(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__SetParameterAttributes(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__GetParameterAttributes(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__AddObject(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__DeleteObject(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__Reboot(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__Download(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__Upload(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__FactoryReset(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__ScheduleInform(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp__TranferComplete(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__Inform(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Inform *cwmp__Inform, struct _cwmp__InformResponse *cwmp__InformResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__GetRPCMethods(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetRPCMethods *cwmp__GetRPCMethods, struct _cwmp__GetRPCMethodsResponse *cwmp__GetRPCMethodsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__GetParameterValues(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetParameterValues *cwmp__GetParameterValues, struct _cwmp__GetParameterValuesResponse *cwmp__GetParameterValuesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__SetParameterValues(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__SetParameterValues *cwmp__SetParameterValues, struct _cwmp__SetParameterValuesResponse *cwmp__SetParameterValuesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__GetParameterNames(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetParameterNames *cwmp__GetParameterNames, struct _cwmp__GetParameterNamesResponse *cwmp__GetParameterNamesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__SetParameterAttributes(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__SetParameterAttributes *cwmp__SetParameterAttributes, struct _cwmp__SetParameterAttributesResponse *cwmp__SetParameterAttributesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__GetParameterAttributes(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__GetParameterAttributes *cwmp__GetParameterAttributes, struct _cwmp__GetParameterAttributesResponse *cwmp__GetParameterAttributesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__AddObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__AddObject *cwmp__AddObject, struct _cwmp__AddObjectResponse *cwmp__AddObjectResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__DeleteObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__DeleteObject *cwmp__DeleteObject, struct _cwmp__DeleteObjectResponse *cwmp__DeleteObjectResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__Reboot(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Reboot *cwmp__Reboot, struct _cwmp__RebootResponse *cwmp__RebootResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__Download(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Download *cwmp__Download, struct _cwmp__DownloadResponse *cwmp__DownloadResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__Upload(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__Upload *cwmp__Upload, struct _cwmp__UploadResponse *cwmp__UploadResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__FactoryReset(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__FactoryReset *cwmp__FactoryReset, struct _cwmp__FactoryResetResponse *cwmp__FactoryResetResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__ScheduleInform(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__ScheduleInform *cwmp__ScheduleInform, struct _cwmp__ScheduleInformResponse *cwmp__ScheduleInformResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp__TranferComplete(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp__TranferComplete *cwmp__TranferComplete, struct _cwmp__TranferCompleteResponse *cwmp__TranferCompleteResponse);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
